query alliances{
  Alliances: getAlliances {
    _id
    name
    title
    color
    heroes{
      Name
      Filename
    }
    alliance_bonus{
        unit_count
        description
    }
    alliance_max_bonus_count
    height
  }
}