query ($allianceName: String!){
  Alliance: getAllianceByName(allianceName: $allianceName) {
    _id
    name
    title
    color
    heroes{
      _id
      Name
      Filename
    }
    alliance_bonus{
        unit_count
        description
    }
    alliance_max_bonus_count
    height
  }
}