query ($heroName: String!){
  Hero: getHeroByName(heroName: $heroName) {
    name
    alliances{
      name
    }
    tier
    tier_1_health
    tier_2_health
    tier_3_health
    mana
    tier_1_dps
    tier_2_dps
    tier_3_dps
    tier_1_ad_min
    tier_1_ad_max
    tier_2_ad_min
    tier_2_ad_max
    tier_3_ad_min
    tier_3_ad_max
    tier_1_attack_rate
    tier_2_attack_rate
    tier_3_attack_rate
    move_speed
    attack_range
    tier_1_magic_resist
    tier_2_magic_resist
    tier_3_magic_resist
    tier_1_armor
    tier_2_armor
    tier_3_armor
    tier_1_health_regen
    tier_2_health_regen
    tier_3_health_regen
    filename
    hero_image
    abilities{
        ability
        ability_image
        description
    }
    lore_text
    ace_ability
    ace_description
  }
}